import type { OxlintConfig } from 'oxlint'
import { vue as _vue, renamePluginInConfigs } from '@antfu/eslint-config'
import { getConfig } from '../utils'

const VUE_RULES_CURRENTLY_NOT_SUPPORTED_LIST = [
  'vue/array-bracket-spacing',
  'vue/arrow-spacing',
  'vue/attribute-hyphenation',
  'vue/attributes-order',
  'vue/block-order',
  'vue/block-spacing',
  'vue/block-tag-newline',
  'vue/brace-style',
  'vue/comma-dangle',
  'vue/comma-spacing',
  'vue/comma-style',
  'vue/comment-directive',
  'vue/component-definition-name-casing',
  'vue/component-name-in-template-casing',
  'vue/component-options-name-casing',
  'vue/component-tags-order',
  'vue/custom-event-name-casing',
  'vue/define-macros-order',
  'vue/dot-location',
  'vue/dot-notation',
  'vue/eqeqeq',
  'vue/first-attribute-linebreak',
  'vue/html-closing-bracket-newline',
  'vue/html-closing-bracket-spacing',
  'vue/html-comment-content-spacing',
  'vue/html-end-tags',
  'vue/html-indent',
  'vue/html-quotes',
  'vue/html-self-closing',
  'vue/jsx-uses-vars',
  'vue/key-spacing',
  'vue/keyword-spacing',
  'vue/max-attributes-per-line',
  'vue/multi-word-component-names',
  'vue/multiline-html-element-content-newline',
  'vue/mustache-interpolation-spacing',
  'vue/no-async-in-computed-properties',
  'vue/no-child-content',
  'vue/no-computed-properties-in-data',
  'vue/no-deprecated-data-object-declaration',
  'vue/no-deprecated-delete-set',
  'vue/no-deprecated-dollar-listeners-api',
  'vue/no-deprecated-dollar-scopedslots-api',
  'vue/no-deprecated-events-api',
  'vue/no-deprecated-filter',
  'vue/no-deprecated-functional-template',
  'vue/no-deprecated-html-element-is',
  'vue/no-deprecated-inline-template',
  'vue/no-deprecated-model-definition',
  'vue/no-deprecated-props-default-this',
  'vue/no-deprecated-router-link-tag-prop',
  'vue/no-deprecated-scope-attribute',
  'vue/no-deprecated-slot-attribute',
  'vue/no-deprecated-slot-scope-attribute',
  'vue/no-deprecated-v-bind-sync',
  'vue/no-deprecated-v-is',
  'vue/no-deprecated-v-on-native-modifier',
  'vue/no-deprecated-v-on-number-modifiers',
  'vue/no-deprecated-vue-config-keycodes',
  'vue/no-dupe-keys',
  'vue/no-dupe-v-else-if',
  'vue/no-duplicate-attributes',
  'vue/no-empty-pattern',
  'vue/no-expose-after-await',
  'vue/no-irregular-whitespace',
  'vue/no-lone-template',
  'vue/no-loss-of-precision',
  'vue/no-multi-spaces',
  'vue/no-mutating-props',
  'vue/no-parsing-error',
  'vue/no-ref-as-operand',
  'vue/no-reserved-component-names',
  'vue/no-reserved-keys',
  'vue/no-reserved-props',
  'vue/no-restricted-syntax',
  'vue/no-restricted-v-bind',
  'vue/no-setup-props-reactivity-loss',
  'vue/no-shared-component-data',
  'vue/no-side-effects-in-computed-properties',
  'vue/no-spaces-around-equal-signs-in-attribute',
  'vue/no-sparse-arrays',
  'vue/no-template-key',
  'vue/no-template-shadow',
  'vue/no-textarea-mustache',
  'vue/no-unused-components',
  'vue/no-unused-refs',
  'vue/no-unused-vars',
  'vue/no-use-computed-property-like-method',
  'vue/no-use-v-if-with-v-for',
  'vue/no-useless-template-attributes',
  'vue/no-useless-v-bind',
  'vue/no-v-for-template-key-on-child',
  'vue/no-v-html',
  'vue/no-v-text-v-html-on-component',
  'vue/no-watch-after-await',
  'vue/object-curly-newline',
  'vue/object-curly-spacing',
  'vue/object-property-newline',
  'vue/object-shorthand',
  'vue/one-component-per-file',
  'vue/operator-linebreak',
  'vue/order-in-components',
  'vue/padding-line-between-blocks',
  'vue/prefer-global/process',
  'vue/prefer-separate-static-class',
  'vue/prefer-template',
  'vue/prop-name-casing',
  'vue/quote-props',
  'vue/require-component-is',
  'vue/require-default-prop',
  'vue/require-explicit-emits',
  'vue/require-prop-type-constructor',
  'vue/require-prop-types',
  'vue/require-render-return',
  'vue/require-slots-as-functions',
  'vue/require-toggle-inside-transition',
  'vue/require-v-for-key',
  'vue/require-valid-default-prop',
  'vue/return-in-computed-property',
  'vue/return-in-emits-validator',
  'vue/singleline-html-element-content-newline',
  'vue/space-in-parens',
  'vue/space-infix-ops',
  'vue/space-unary-ops',
  'vue/template-curly-spacing',
  'vue/this-in-template',
  'vue/use-v-on-exact',
  'vue/v-bind-style',
  'vue/v-on-event-hyphenation',
  'vue/v-on-style',
  'vue/v-slot-style',
  'vue/valid-attribute-name',
  'vue/valid-define-options',
  'vue/valid-next-tick',
  'vue/valid-template-root',
  'vue/valid-v-bind',
  'vue/valid-v-cloak',
  'vue/valid-v-else',
  'vue/valid-v-else-if',
  'vue/valid-v-for',
  'vue/valid-v-html',
  'vue/valid-v-if',
  'vue/valid-v-is',
  'vue/valid-v-memo',
  'vue/valid-v-model',
  'vue/valid-v-on',
  'vue/valid-v-once',
  'vue/valid-v-pre',
  'vue/valid-v-show',
  'vue/valid-v-slot',
  'vue/valid-v-text',
  'node/prefer-global/process',
]

export async function vue(): Promise<OxlintConfig> {
  const configItems = renamePluginInConfigs(await _vue(), { ts: 'typescript' })
  const globals: any = getConfig(configItems, 'antfu/vue/setup').languageOptions?.globals
  const rules: any = getConfig(configItems, 'antfu/vue/rules').rules
  for (const key in rules) {
    if (key.startsWith('antfu'))
      delete rules[key]
    if (VUE_RULES_CURRENTLY_NOT_SUPPORTED_LIST.includes(key))
      // Currently does not supported by oxlint, see
      // https://github.com/oxc-project/oxc/issues/11440
      delete rules[key]
  }
  return {
    plugins: [],
    overrides: [
      {
        files: ['**/*.vue'],
        plugins: ['vue'],
        globals,
        rules,
      },
    ],
  }
}
